### PR TITLE
Python-3 compatibility

### PR DESCRIPTION
**Pull request by pastewka**
Updated hotbit to support Python 3

- Print functions
- Integer divisions using //
- C-module follows new API
- Update some deprecated ASE imports

### CODE REVIEW

**Comment by ajjackson** [comment]
This is giving me a few errors in testing with ASE v3.13, related to the missing "force_consistent" keyword to `atoms.get_potential_energy()`. I'm also getting some RuntimeWarnings about the numpy doubles math.

This is further developed than my attempt in #6 . I suggest closing that one and put finishing touches here!

Do you have any insight as to why it was necessary to change the assertion criterion? It seems strange that ASE changes would cause numerical differences.

**Comment by pastewka** [comment]
I’ll check what the v3.13 problem is. Not sure where the change in assertion comes from, is it really linked to ASE version? I believe it is not ASE but maybe numpy version. I’m also running on cygwin, all these things can give tiny roundoff errors.
 
Best,
Lars

**Comment by ajjackson** [comment]
OK, there were two things going on with `force_consistent`:
a) ASE now expects to find this in calculators, and receive a special Error if it's not implemented. The Optimize classes look for this Error to decide whether to use `force_consistent` if it's not specified.
b) Version 3.13 has a bug which has now been fixed in the development version, which broke the logic for a) so the error was occurring even *with* the correction to Hotbit.

I have added the Error behaviour, and also specified `force_consistent=False` in the test that was raising the error, so that the broken logic in 3.13 is bypassed anyway.

**Comment by pastewka** [comment]
Okay, thanks!

**Comment by pastewka** [comment]
Note that this merge request maintains Python-2 compatibility. I'll try to set up automated testing on Travis-CI for Python-2 and Python-3 to make sure compatibility for both Python versions is not broken.

**Comment by ajjackson** [comment]
I see the origin of the numpy warnings now: they are caused by trying to do "Bravais lattice" calculations with the [[0,0,0],[0,0,0],[0,0,0]] unit cell which is now the default in ASE. I don't really understand the "containers" aspect of Hotbit well enough to fix this, but presumably the derived nonsense values are not being used in any case? Why is the Bravais lattice module being called in the case of a hydrogen molecule? 

I think this can probably be regarded as a general Hotbit issue rather than an ASE/Python3 compatibility issue.

**Comment by ajjackson** [comment]
Aside from that Bravais lattice issue, this is now passing all tests for me (except MIO, I don't know how to set that up) with Python 2.7 and 3.6, both with ASE 3.13 and the development Git version.

**Comment by pastewka** [comment]
For the mio test, download the parameter set here:

[http://www.dftb.org/parameters/download/mio/mio-1-1-cc/](http://www.dftb.org/parameters/download/mio/mio-1-1-cc/)

And then point the MIO_0_1 environment variable to where you extracted the parameters.

**Pull request merged**
